version: '3.8'
services:
  backend:
    build:
      context: ./react-backend/react-project-backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./react-frontend/react-project-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
